tuirer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="home"), 
        
    path('', include('tuites.urls')), 
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tuites/urls.py
from django.urls import path

from tuites.views import PostTuiteView, LikeTuiteView

app_name = "tuites"

urlpatterns = [
    path('postar/', PostTuiteView.as_view(), name='post'),
    path('like/<int:pk>', LikeTuiteView.as_view(), name='like'),
]

users/urls.py
from django.urls import path

from users.views import (
    ProfileView, 
    ProfileEditView, 
    UserLoginView,
    UserLogoutView,
    UserSignupView, 
)

app_name = 'users'

urlpatterns = [    
    path('perfil/<int:pk>/', ProfileView.as_view(), name='profile'), 
    path('perfil/<int:pk>/editar/', ProfileEditView.as_view(), name='profile-edit'), 
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'), 
    path('signup/', UserSignupView.as_view(), name='signup'),
]

core/models.py
from django.db import models

# Create your models here.

tuites/models.py
from django.db import models

from tuites.managers import TuitesManager


# Create your models here.
class Tuite(models.Model):
    content = models.CharField('Tuite', max_length=280)
    author = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='tuites')
    date_created = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField('users.User', blank=True) # queryset dos usuário que gostaram do tweet


    objects = TuitesManager()

    @property
    def likes_count(self):
        return self.liked_by.count() 

    def __str__(self):
        return f'{self.author.username}: {self.content}'

    class Meta:
        ordering = ('-date_created', )
# related_name: como eu posso acessar os Tuites a partir do model que é author

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    picture = models.ImageField('Foto de perfil', default='/img/blank-profile.png')
    following = models.ManyToManyField('self', blank=True)

tuites/forms.py
from django import forms

from tuites.models import Tuite


class PostTuiteForm(forms.ModelForm):
    class Meta:
        model = Tuite
        fields = ('content', 'author')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].initial = self.initial['user'].id
        self.fields['author'].widget = forms.HiddenInput()
        # self.fields['content'].help_text = 'Digite o que vocês está pensando aqui'
        # self.fields['content'].widget = forms.TextInput(attrs={'class': 'post-tuite-input'})

    def clean(self):
        cleaned_data = super().clean()
        content = self.cleaned_data.get('content')
        
        if 'Temer' in content:
            raise forms.ValidationError('FORA TEMER')

        if not self.initial.get('user') == cleaned_data.get('author'):
            raise forms.ValidationError('Não tente burlar o sistema!')

        return cleaned_data

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User

class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')
    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_exists = User.objects.filter(email=email).exists()
        if user_exists:
            raise forms.ValidationError('Um usuário com este e-mail já existe!')
        return email 

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from tuites.models import Tuite


# Create your views here.
def index(request):
    context = {
        "now": datetime.now(),
        "tuites": Tuite.objects.all(), 
    }
    return render(request, 'home.html', context)

tuites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, RedirectView

from tuites.forms import PostTuiteForm
from tuites.models import Tuite


class PostTuiteView(LoginRequiredMixin, CreateView):
    model = Tuite
    template_name = 'post_tuite.html'
    form_class = PostTuiteForm
    success_url = reverse_lazy('tuites:post')

    def get_initial(self):
        return {
            'user': self.request.user
        }

    # https://docs.djangoproject.com/en/2.0/ref/contrib/messages/
    def form_valid(self, form):
        messages.success (
            self.request,
            'Você postou um tuite!'
        )
        return super().form_valid(form)


class LikeTuiteView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        from_url = self.request.META.get('HTTP_REFERER')
        tuite_pk = kwargs.get('pk')
        user = self.request.user
        
        tuite = Tuite.objects.get(pk=tuite_pk)
        if tuite.liked_by.filter(pk=user.pk).exists():
            tuite.liked_by.remove(user)
        else:
            tuite.liked_by.add(user)
        # add e remove são usados quando temos que lidar com ManyToMany
         
        return reverse_lazy('home')

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from users.forms import UserSignupForm
from users.mixins import ProfileAccessMixin
from users.models import User


class ProfileView(DetailView):
    model = User
    template_name = 'profile.html'
    context_object_name = 'profile'
    ''''por padrão, o context_object_name é o nome do model (antes de definir
    que era 'profile', estava 'user')'''


class ProfileEditView(ProfileAccessMixin, UpdateView):
    model = User
    fields = ('picture', 'username', )
    template_name = 'profile_edit.html'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.object.pk])


class UserLoginView(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True


class UserLogoutView(LogoutView):
    pass


class UserSignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = 'signup.html'
    success_url = reverse_lazy('tuites:post') 


#UpdateView é a view usada para editar um objeto

templates/base.html
{% load staticfiles %}

<! doctype <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tuirer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>

    {% include "includes/menu.html" %}
    
    <div class="block-content">
        {% block content %}
        {% endblock %}
    </div>
    
    <footer>
        <div class="tuirer-footer">
            <h3>Thanks for visiting us</h3>
        </div>
    </footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div>
    {% for tuite in tuites %}
        {% include "includes/card.html" %}
    {% endfor %}
    </div>


{% endblock %}

templates/includes/card.html
{% load tuites_likes %}

<div class="card">
    <p class="content">{{ tuite.content }}</p>
    <hr>
    <div class="author-and-likes">
        <a href="{% url 'users:profile' tuite.author.pk %}" class="author"> <!-- Adiciona link para o perfil do usuário -->
            <div class="author-avatar" style="background-image: url('{{ tuite.author.picture.url }}');"></div>
            {{ tuite.author }} 
        </a>
        <div class="likes">
            <a href="{% url 'tuites:like' tuite.pk %}">
                {% tuite_liked_icon %}
                {{ tuite.likes_count }}
            </a>
        </div>
        <div class="likes-list">
            {% if tuite.likes_count > 0 %}
                Curtido por:
                {% for user in tuite.liked_by.all %}
                {{ user }}
                {% endfor %}
            {% endif %}
        </div>
    </div>
    </a>
</div>

templates/includes/menu.html
<nav>
    <div class="menu">
        <a href="{% url 'home' %}" class="tuirer-title">Tuirer</a>
        <div class="submenu">
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' request.user.pk %}" class="redirect">Hello, {{ request.user.username }}</a>
                
            {% else %}
                <a href="{% url 'users:login' %}">Login</a>        
            {% endif %}
            <a href="{% url 'tuites:post' %}" class="nav-link">Post</a>
            {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}" class="redirect">Sair</a>
            {% endif %}
        </div>
    </div>
</nav>

templates/login.html
{% extends "base.html" %}

{% block content %}

    <div class="login-content">
        <div class="login-title">Tuirer - Login</div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login">
        </form>

    </div>

{% endblock %}

templates/post_tuite.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    {% if form.errors %}
        {% for error in form.non_field_errors %}
            <p class="error">{{error}}</p>
        {% endfor %}
    {% endif %}

    {% if success_message %}
        <p class="message">{{ success_message }}</p>
    {% endif %}

    <form method="POST" id="post-form">
        {% csrf_token %}

        {% for field in form %}
            {% if not field.name == 'author' %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% endif %}

            {% render_field field class="post-tuite-field" placeholder=field.label autofocus=True %}
            <p>{{ field.help_text }}</p>
            {{ field.errors }}
        {% endfor %}

        <input type="submit" value="Postar Tuite" />
        
    </form>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="profile">
    <div class="profile-picture" style="background-image: url('{{ profile.picture.url }}');"></div>
    {% if profile == request.user %}
        <a href="{% url 'users:profile-edit' request.user.pk %}" id="edit-button">Edit profile</a>
    {% endif %}
    <h2 class="profile-title">Welcome, {{ profile }}!</h2>
    {{ profile.email }}

    <div>
        {% for tuite in profile.tuites.all %}
            {% include "includes/card.html" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/profile_edit.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'users:profile' request.user.pk %}">Voltar para o seu perfil</a>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
    </form>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
    <div class="login-content">
        <div class="login-title">Tuirer - SignUp</div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="SignUp">
        </form>

    </div>
{% endblock content %}  